sudo: enabled
language: python
python:
  - "2.7"
install: 
  - "pip install -r requirements.txt"
  - "mkdir geckodriver"
  - "wget https://github.com/mozilla/geckodriver/releases/download/v0.18.0/geckodriver-v0.18.0-linux64.tar.gz"
  - "tar -xvf geckodriver-v0.18.0-linux64.tar.gz -C geckodriver"
  - "sudo cp geckodriver/geckodriver /usr/local/bin/"

addons:
  firefox: latest

# boilerplate: https://docs.travis-ci.com/user/gui-and-headless-browsers/
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

script: "python functional_tests.py"
