language: python
python:
  - "2.7"
install: "pip install -r requirements.txt"

addons:
  firefox: latest

# boilerplate: https://docs.travis-ci.com/user/gui-and-headless-browsers/
before_script:
  - "mkdir geckodriver"
  - "wget https://github.com/mozilla/geckodriver/releases/download/v0.18.0/geckodriver-v0.18.0-arm7hf.tar.gz"
  - "tar -xzf geckodriver-v0.18.0-arm7hf.tar.gz geckodriver"
  - "cp geckodriver/geckodriver /usr/local/bin/geckodriver"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

script: "python functional_tests.py"
